apiVersion: 1

datasources:
  - name: Mock Prometheus
    type: prometheus
    uid: prometheus-main
    url: http://mock-prometheus:9090
    access: proxy
    isDefault: false

  - name: MongoDB Mock Prometheus
    type: prometheus
    uid: prometheus-mongo
    url: http://mock-mongo-prometheus:9090
    access: proxy
    isDefault: false

  - name: Probe Metrics
    type: prometheus
    uid: probe-metrics
    url: http://prometheus:9090
    access: proxy
    isDefault: true
