{
 "title": "MongoDB Atlas System Metrics",
 "description": "MongoDB Atlas System Metrics collected with official Prometheus integration. Normalized from Grafana dashboard 19654 for the Dashboard SRE demo.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Interval", "query": "30s,1m,5m,1h,1d" },
   { "name": "job", "query": { "query": "label_values(mongodb_up, job)" } },
   {
    "name": "group_id",
    "label": "Group Id",
    "query": {
     "query": "label_values(mongodb_up{job=\"$job\"}, group_id)"
    }
   },
   {
    "name": "cl_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id'}, cl_name)"
    }
   },
   {
    "name": "rs_nm",
    "label": "ReplicaSet Name",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name'}, rs_nm)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name',rs_nm='$rs_nm'},instance)"
    }
   },
   {
    "name": "process_port",
    "label": "Process Port",
    "query": {
     "query": "label_values(mongodb_up{group_id='$group_id', cl_name='$cl_name',rs_nm='$rs_nm'},process_port)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Group Metadata",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace( sum(mongodb_up{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by ( group_id, org_id, rs_nm, cl_name), \"hostname\", \"$1\", \"instance\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Cluster host list",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace( sum(mongodb_info{group_id=~\"$group_id\", cl_name=~\"$cl_name\", instance=~\"$host.*\"}) by (instance, replica_state_name, process_port, rs_nm, process_type), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory - Resident",
   "type": "graph",
   "description": "The number of megabytes resident. MMAPv1: It is typical over time, on a dedicated database server, for this number to approach the amount of physical ram on the box. WiredTiger: In a standard deployment resident is the amount of memory used by the WiredTiger cache plus the memory dedicated to other in memory structures used by the mongod process. By default, mongod with WiredTiger reserves 50% of the total physical memory on the server for the cache and at steady state, WiredTiger tries to limit cache usage to 80% of that total. For example, if a server has 16GB of memory, WiredTiger will assume it can use 8GB for cache and at steady state should use about 6.5GB.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_mem_resident{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Memory - Virtual",
   "type": "graph",
   "description": "The virtual megabytes for the mongod process. MMAPv1: Generally virtual should be a little larger than mapped (or 2x with --journal), but if virtual is many gigabytes larger, it indicates that excessive memory is being used by other aspects than the memory mapping of files -- that would be bad/suboptimal. The most common case of usage of a high amount of memory for non-mapped is that there are very many connections to the database. Each connection has a thread stack and the memory for those stacks can add up to a considerable amount. WiredTiger: Generally virtual should be a little larger than mapped, but if virtual is many gigabytes larger, it indicates that excessive memory is being used by other aspects than the memory mapping of files -- that would be bad/suboptimal. The most common case of usage of a high amount of memory for non-mapped is that there are very many connections to the database. Each connection has a thread stack and the memory for those stacks can add up to a considerable amount.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_mem_virtual{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Asserts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Asserts - Regular",
   "type": "graph",
   "description": "The average rate of regular asserts raised per second over the selected sample period\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(mongodb_asserts_regular{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Asserts - Warning",
   "type": "graph",
   "description": "The average rate of warnings per second over the selected sample period",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(mongodb_asserts_warning{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Asserts - Message",
   "type": "graph",
   "description": "The average rate of message asserts per second over the selected sample period. These are internal server errors that have a well defined text string. Stack traces are logged for these",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(mongodb_asserts_msg{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Asserts - User",
   "type": "graph",
   "description": "The average rate of user asserts per second over the selected sample period. These are errors that can be generated by a user such as out of disk space or duplicate key",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(mongodb_asserts_user{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Cache Activity - Read Into",
   "type": "graph",
   "description": "The average rate of bytes per second read into WiredTiger's cache over the selected sample period.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_wiredTiger_cache_bytes_read_into_cache{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Cache Activity - Write From",
   "type": "graph",
   "description": "The average rate of bytes per second written from WiredTiger's cache over the selected sample period.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_wiredTiger_cache_bytes_written_from_cache{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Cache Usage - Used",
   "type": "graph",
   "description": "The number of bytes currently in the WiredTiger cache.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_wiredTiger_cache_bytes_currently_in_the_cache{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Cache Usage - Dirty",
   "type": "graph",
   "description": "The number of tracked dirty bytes currently in the WiredTiger cache.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_wiredTiger_cache_tracked_dirty_bytes_in_the_cache{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Connections - Current",
   "type": "graph",
   "description": "The number of currently active connections to this server. A stack is allocated per connection; thus very many connections can result in significant RAM usage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_connections_current{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Cursors - Total Open",
   "type": "graph",
   "description": "The number of cursors that the server is maintaining for clients. Because MongoDB exhausts unused cursors, typically this value is small or zero. However, if there is a queue, stale tailable cursors, or a large number of operations this value may rise.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_metrics_cursor_open_total{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Cursors - Timed Out",
   "type": "graph",
   "description": "The average rate of cursors that have timed out per second over the selected sample period",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_metrics_cursor_timedOut{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Document Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Document Metrics - Returned",
   "type": "graph",
   "description": "The average rate per second of documents returned by queries over the selected sample period.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_document_returned{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Document Metrics - Inserted",
   "type": "graph",
   "description": "The average rate per second of documents inserted over the selected sample period.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_document_inserted{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Document Metrics - Updated",
   "type": "graph",
   "description": "The average rate per second of documents updated over the selected sample period.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_document_updated{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Document Metrics - Deleted",
   "type": "graph",
   "description": "The average rate per second of documents deleted over the selected sample period.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_document_deleted{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Network - Num Requests",
   "type": "graph",
   "description": "The average rate of requests sent to this database server per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_network_numRequests{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Network - Bytes In",
   "type": "graph",
   "description": "The average rate of physical (after any wire compression) bytes sent to this database server per second over the selected sample period",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_network_bytesIn{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "rx - {{hostname}}:{{process_port}}"
    },
    {
     "expr": "label_replace(-1 * sum(irate(mongodb_network_bytesOut{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "tx - {{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Opcounters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Opcounters - Command",
   "type": "graph",
   "description": "The average rate of commands performed per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_command{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Opcounters - Query",
   "type": "graph",
   "description": "The average rate of queries performed per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_query{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Opcounters - Update",
   "type": "graph",
   "description": "The average rate of updates performed per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_update{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Opcounters - Delete",
   "type": "graph",
   "description": "The average rate of deletes performed per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_delete{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Opcounters - Getmore",
   "type": "graph",
   "description": "The average rate of getMores performed per second on any cursor over the selected sample period. On a primary, this number can be high even if the query count is low as the secondaries \"getMore\" from the primary often as part of replication.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_getmore{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Opcounters - Insert",
   "type": "graph",
   "description": "The average rate of inserts performed per second over the selected sample period",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opcounters_insert{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Operation Execution Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Operation Execution Times - Avg Ms/Read",
   "type": "graph",
   "description": "The average execution time in milliseconds per read operation over the selected sample period.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opLatencies_reads_latency{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])/irate(mongodb_opLatencies_reads_ops{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Operation Execution Times - Avg Ms/Write",
   "type": "graph",
   "description": "The average execution time in milliseconds per write operation over the selected sample period.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opLatencies_writes_latency{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])/irate(mongodb_opLatencies_writes_ops{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Operation Execution Times - Avg Ms/Command",
   "type": "graph",
   "description": "The average execution time in milliseconds per command operation over the selected sample period.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_opLatencies_commands_latency{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])/irate(mongodb_opLatencies_commands_ops{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Page Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "The average rate of page faults on this process per second over the selected sample period. In non-Windows environments this is hard page faults only.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_extra_info_page_faults{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Query Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Query Executor - Scanned",
   "type": "graph",
   "description": "The average rate per second over the selected sample period of index items scanned during queries and query-plan evaluation. This rate is driven by the same value as totalKeysExamined in the output of explain().",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_queryExecutor_scanned{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Query Executor - Scanned Objects",
   "type": "graph",
   "description": "The average rate per second over the selected sample period of documents scanned during queries and query-plan evaluation. This rate is driven by the same value as totalDocsExamined in the output of explain().",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_queryExecutor_scannedObjects{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Queues - Total",
   "type": "graph",
   "description": "The number of operations queued waiting for any lock",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_globalLock_currentQueue_total{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Queues - Readers",
   "type": "graph",
   "description": "The number of operations queued waiting for a read lock",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_globalLock_currentQueue_readers{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Queues - Writers",
   "type": "graph",
   "description": "The number of operations queued waiting for a write lock",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_globalLock_currentQueue_writers{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Scan and Order", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Scan and Order",
   "type": "graph",
   "description": "The average rate per second over the selected sample period of queries that return sorted results that cannot perform the sort operation using an index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "yaxes": [
    { "format": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(mongodb_metrics_operation_scanAndOrder{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}[1m])) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  { "title": "Tickets Available", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Tickets Available - Reads",
   "type": "graph",
   "description": "The number of read tickets available to the WiredTiger storage engine. Read tickets represent the number of concurrent read operations allowed into the storage engine. When this value reaches zero new read requests may queue until a read ticket becomes available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_wiredTiger_concurrentTransactions_read_available{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  },
  {
   "title": "Tickets Available - Writes",
   "type": "graph",
   "description": "The number of write tickets available to the WiredTiger storage engine. Write tickets represent the number of concurrent write operations allowed into the storage engine. When this value reaches zero new write requests may queue until a write ticket becomes available.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(mongodb_wiredTiger_concurrentTransactions_write_available{group_id=~\"$group_id\", cl_name=~\"$cl_name\", rs_nm=~\"$rs_nm\", instance=~\"$host.*\",  process_port=~\"$process_port\"}) by (instance, process_port) , \"hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{hostname}}:{{process_port}}"
    }
   ]
  }
 ]
}